---
require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-rake
  - rubocop-capybara

AllCops:
    NewCops: enable
    TargetRubyVersion: 2.7
    Exclude:
        - 'bin/**/*'
        - 'tmp/**/*'
        - 'vendor/**/*'

Bundler/OrderedGems:
    Enabled: false

Style/Alias:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/NumericLiterals:
    Enabled: false

Style/TrailingCommaInArrayLiteral:
    Enabled: false

Style/TrailingCommaInHashLiteral:
    Enabled: false

Style/TrailingCommaInArguments:
    Enabled: false

Style/Documentation:
    Enabled: false

Style/DoubleNegation:
    Enabled: false

Style/WordArray:
    Enabled: false

Style/ClassAndModuleChildren:
    Enabled: false

Layout/EndOfLine:
   EnforcedStyle: lf

Layout/TrailingEmptyLines:
    Enabled: true

Layout/LineLength:
    Max: 120
    Enabled: false
    AllowedPatterns:
        - 'it .* do$'
        - 'context .* do$'
        - 'scenario .* do$'

Metrics/ClassLength:
    Enabled: false

Metrics/MethodLength:
    Max: 50
    Exclude:

Metrics/AbcSize:
    Max: 25 # TODO: Restore to '20'
    Exclude:
        - 'spec/**/*'

Metrics/BlockLength:
    Max: 40
    Exclude:
        - 'spec/**/*'

RSpec/ContextWording:
    Prefixes:
      - when
      - with
      - without
      - and

Metrics/ModuleLength:
    Exclude:
        - 'spec/ccs/frontend_helpers/**/*'
        - 'spec/ccs/components/**/*'

RSpec/MultipleMemoizedHelpers:
    Enabled: false

RSpec/VariableName:
    Enabled: false

Naming/VariableNumber:
    Enabled: false

Lint/MissingSuper:
    Enabled: false

Rails/HelperInstanceVariable:
    Enabled: false

Style/OptionalBooleanParameter:
    Enabled: false

RSpec/VerifiedDoubleReference:
    Enabled: false

RSpec/NestedGroups:
    Max: 5

RSpec/ExampleLength:
    Exclude:
        - 'spec/ccs/frontend_helpers/**/*'
        - 'spec/ccs/components/**/*'

Rails/DynamicFindBy:
  Whitelist:
    - find_by_id

RSpec/MultipleExpectations:
    Max: 3

RSpec/FilePath:
    CustomTransform:
        GovUKFrontend: govuk_frontend
        GovUK: govuk
