---
plugins:
    - rubocop-rails
    - rubocop-rake
    - rubocop-rspec

require:
    - rubocop-capybara

AllCops:
    NewCops: enable
    TargetRubyVersion: 3.2
    Exclude:
        - "bin/**/*"
        - "tmp/**/*"
        - "vendor/**/*"

# Capyabara rubocop config
Capybara:
    Enabled: true

# Rails rubocop config
Rails:
    Enabled: true

Rails/HelperInstanceVariable:
    Enabled: false

Rails/DynamicFindBy:
    Whitelist:
        - find_by_id

Rails/FilePath:
    Enabled: false

Rails/OutputSafety:
    Exclude:
        - "spec/ccs/frontend_helpers/**/*fixtures_spec.rb"

# RSpec rubocop config
RSpec:
    Enabled: true

RSpec/ContextWording:
    Prefixes:
        - when
        - with
        - without
        - and

RSpec/MultipleMemoizedHelpers:
    Enabled: false

RSpec/VariableName:
    Enabled: false

RSpec/VerifiedDoubleReference:
    Enabled: false

RSpec/NestedGroups:
    Max: 5

RSpec/ExampleLength:
    Exclude:
        - "spec/ccs/frontend_helpers/**/*"
        - "spec/ccs/components/**/*"

RSpec/MultipleExpectations:
    Max: 3

RSpec/SpecFilePathFormat:
    CustomTransform:
        GovUKFrontend: govuk_frontend
        GovUK: govuk

# Standard rubocop config
Bundler/OrderedGems:
    Enabled: false

Style/Alias:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/NumericLiterals:
    Enabled: false

Style/TrailingCommaInArrayLiteral:
    Enabled: false

Style/TrailingCommaInHashLiteral:
    Enabled: false

Style/TrailingCommaInArguments:
    Enabled: false

Style/Documentation:
    Enabled: false

Style/DoubleNegation:
    Enabled: false

Style/WordArray:
    Enabled: false

Style/ClassAndModuleChildren:
    Enabled: false

Layout/EndOfLine:
    EnforcedStyle: lf

Layout/TrailingEmptyLines:
    Enabled: true

Layout/LineLength:
    Max: 120
    Enabled: false
    AllowedPatterns:
        - "it .* do$"
        - "context .* do$"
        - "scenario .* do$"

Lint/UselessConstantScoping:
    Enabled: false

Metrics/ClassLength:
    Enabled: false

Metrics/MethodLength:
    Max: 50
    Exclude:

Metrics/AbcSize:
    Max: 25 # TODO: Restore to '20'
    Exclude:
        - "spec/**/*"

Metrics/BlockLength:
    Max: 40
    Exclude:
        - "spec/**/*"

Metrics/ModuleLength:
    Exclude:
        - "spec/ccs/frontend_helpers/**/*"
        - "spec/ccs/components/**/*"

Naming/VariableNumber:
    Enabled: false

Lint/MissingSuper:
    Enabled: false

Style/OptionalBooleanParameter:
    Enabled: false
