name: Publish the gem to RubyGems

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Get package version
        id: package_version
        run: |
          echo "ruby=$(./bin/version)" >> $GITHUB_OUTPUT
          echo "ruby_semver=$(./bin/semver)" >> $GITHUB_OUTPUT

      - name: Check if version tag already exists
        id: version_tag
        uses: mukunku/tag-exists-action@bdad1eaa119ce71b150b952c97351c75025c06a9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: v${{ steps.package_version.outputs.ruby }}

      - name: Publish packaged to RubyGems
        if: ${{ steps.version_tag.outputs.exists == 'false' }}
        uses: rubygems/release-gem@v1

      - name: Get Changelog Entry
        if: ${{ steps.version_tag.outputs.exists == 'false' }}
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: warn
          version: ${{ steps.package_version.outputs.ruby_semver }}

      - name: Create GitHub release
        if: ${{ steps.version_tag.outputs.exists == 'false' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.package_version.outputs.ruby }}
          name: CCS Frontend Helpers v${{ steps.package_version.outputs.ruby }}
          prerelease: ${{ contains(steps.package_version.outputs.ruby, 'beta') }}
          body: ${{ steps.changelog_reader.outputs.changes }}
